quarkus.package.main-class=GpuLlama3QuarkusChatDemo

quarkus.langchain4j.gpu-llama3.enable-integration=true
quarkus.langchain4j.gpu-llama3.chat-model.model-name=unsloth/Llama-3.2-1B-Instruct-GGUF
quarkus.langchain4j.gpu-llama3.chat-model.quantization=F16
quarkus.langchain4j.gpu-llama3.chat-model.temperature=0.0
quarkus.langchain4j.gpu-llama3.chat-model.max-tokens=64
